### ISSUE TITLE
Wrong character

### ISSUE THREAD

**Issue by HaoHoo** [MicrosoftDocs/architecture-center.zh-cn#75]
localization issue
肜 should be 用

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d0bdc71b-0a54-4cc4-1b79-f60e274e9a51
* Version Independent ID: 1783570c-3545-71c8-72d3-d5657f77c070
* Content: [选择机器学习技术](https://docs.microsoft.com/zh-cn/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning?toc=%2Fzh-cn%2Fazure%2Fmachine-learning%2Fstudio%2Ftoc.json&bc=%2Fzh-cn%2Fazure%2Fbread%2Ftoc.json)
* Content Source: [docs/data-guide/technology-choices/data-science-and-machine-learning.md](https://github.com/microsoftdocs/architecture-center.zh-cn/blob/live/docs/data-guide/technology-choices/data-science-and-machine-learning.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hello, @HaoHoo 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @ishasahni1 
I'm assigning this to you because the requested on an older version, as the ZHCN new version was not localized due to a repo organization change.
Please let us know how we should proceed

**Comment by ishasahni1** [comment]
@CeciAc this repo is now getting localized. I see this topic was localized 8 days ago. Can you kindly review and confirm if this issue is now addressed in the new file.

**Comment by CeciAc** [comment]
@ishasahni1 the production team needs the new location of the file to confirm this change

**Comment by ishasahni1** [comment]
@CeciAc At this point of time we are localizing from Public repo, so the location of the file is https://github.com/microsoftdocs/architecture-center.zh-cn/blob/live/docs/data-guide/technology-choices/data-science-and-machine-learning.md.

Please let me know if this helps.

**Comment by CeciAc** [comment]
Hello, @HaoHoo

Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning?toc=%2Fzh-cn%2Fazure%2Fmachine-learning%2Fstudio%2Ftoc.json&bc=%2Fzh-cn%2Fazure%2Fbread%2Ftoc.json

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
