### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by really10** [MicrosoftDocs/architecture-center.zh-cn#76]
The "Book hotel room" should be translate to "预定酒店房间" rather than "书籍酒店房间".

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [命令和查询责任分离 (CQRS) 模式 - Cloud Design Patterns](https://docs.microsoft.com/zh-cn/azure/architecture/patterns/cqrs#feedback)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center.zh-cn/blob/live/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @really10
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @really10 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/architecture/patterns/cqrs#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
